### PR TITLE
Try to Support Kodi to DM820, DM7080 and DM900/920

### PR DESCRIPTION
**Pull request by fairbird**

### CODE REVIEW

**Comment by persianpros** [comment]
Please don't accept any Kodi related things in pli-extras as it's going to fuck up pli-extras at some point, I will revert them all tomorrow

**Comment by Hains** [comment]
@fairbird 
Read post persianpros.

**Comment by persianpros** [comment]
Everything went back in time via time machine LOL

There is no need to merge then revert, your changes are here: https://github.com/PLi-metas/meta-dream/pulls?q=is%3Apr+is%3Aclosed

We could have a kodi branch but not in develop which should be ok for everybody.

**Comment by fairbird** [comment]
Ok...

**Pull request merged**
